openapi: 3.0.1
info:
  version: 0.0.1
  title: secure-echo

paths:
  /echo:
    post:
      summary: POST a body and receive it back
      operationId: postEcho
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/Message"
      responses:
        '201':
          description: POST echo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        '401':
          description: not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
              example: "not authorized"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - apiKey: []
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    Message:
      properties:
        msg:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
