openapi: 3.0.1
info:
  version: 0.0.1
  title: secure-echo
  contact:
    name: Stefan Junker
    email: mail@stefanjunker.de

tags:
  - name: unsecured
    description: All unsecured resources

paths:
  /echo:
    post:
      summary: POST a body and receive it back
      operationId: postEcho
      tags:
        - secured
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/Message"
      responses:
        '201':
          description: POST echo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        '401':
          description: not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
              example: "not authorized"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - apiKey: []
        - googleOpenId:
          - email

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
    googleOpenId:   # <--- Arbitrary name for the security scheme. Used to refer to it from elsewhere.
      type: openIdConnect
      openIdConnectUrl: https://accounts.google.com/.well-known/openid-configuration
  schemas:
    Message:
      properties:
        msg:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string